import {
  Home,
  Sparkles,
  MessageCircle,
  Trophy,
  Upload,
  History,
  User,
  Key,
  CreditCard,
  LayoutGrid,
  Zap,
  ListChecks,
  TrendingUp,
  BarChart3,
  Sun,
  Calendar,
  List,
  CalendarDays,
  Dumbbell,
  Moon,
  Utensils,
  ShoppingCart,
  Repeat,
  BookOpen,
  Heart,
  Compass,
  Layers,
  CheckSquare,
  Wallet,
  Settings2,
  Users,
  FileCog,
  Download,
  ClipboardList,
  MessageCircleHeart,
  Settings,
  HelpCircle,
  Bug,
  AlertTriangle,
  Activity,
  Target,
  Clock,
  Feather,
  RefreshCw,
  Award,
  Search,
  Map,
  Lock,
  Briefcase,
  Star,
  type LucideIcon,
} from 'lucide-react';

// Map of string icon names to Lucide icon components
const ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  sparkles: Sparkles,
  message: MessageCircle,
  trophy: Trophy,
  upload: Upload,
  history: History,
  user: User,
  key: Key,
  'credit-card': CreditCard,
  'layout-grid': LayoutGrid,
  zap: Zap,
  'list-checks': ListChecks,
  'trending-up': TrendingUp,
  'bar-chart-3': BarChart3,
  sun: Sun,
  calendar: Calendar,
  list: List,
  'calendar-days': CalendarDays,
  dumbbell: Dumbbell,
  moon: Moon,
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  repeat: Repeat,
  'book-open': BookOpen,
  heart: Heart,
  compass: Compass,
  layers: Layers,
  'check-square': CheckSquare,
  'message-circle': MessageCircle,
  wallet: Wallet,
  'settings-2': Settings2,
  users: Users,
  'file-cog': FileCog,
  download: Download,
  'clipboard-list': ClipboardList,
  'message-circle-heart': MessageCircleHeart,
  settings: Settings,
  'help-circle': HelpCircle,
  bug: Bug,
  'alert-triangle': AlertTriangle,
  activity: Activity,
  target: Target,
  clock: Clock,
  feather: Feather,
  'refresh-cw': RefreshCw,
  award: Award,
  search: Search,
  map: Map,
  lock: Lock,
  briefcase: Briefcase,
  star: Star,
};

/**
 * Get a Lucide icon component from a string icon name
 * Returns a fallback Sparkles icon if the name is not found
 */
export function getIcon(iconName: string | undefined): LucideIcon {
  if (!iconName) return Sparkles;
  return ICON_MAP[iconName] || Sparkles;
}

/**
 * Check if an icon name exists in the map
 */
export function hasIcon(iconName: string): boolean {
  return iconName in ICON_MAP;
}
