workflows:
  ios-capacitor:
    name: Capacitor iOS Build (App Store)
    max_build_duration: 60
    environment:
      node: 20
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - build/**/*
