import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Download, Calendar, FileText, Share2, Check, Loader2 } from "lucide-react";
import { useState } from "react";
import { useRoute, useLocation } from "wouter";
import { useToast } from "@/hooks/use-toast";

type ExportFormat = "ics" | "pdf" | "share";

interface ExportOption {
  id: ExportFormat;
  label: string;
  description: string;
  icon: typeof Download;
}

const EXPORT_OPTIONS: ExportOption[] = [
  {
    id: "ics",
    label: "Calendar File (ICS)",
    description: "Import into Apple Calendar, Google Calendar, Outlook, etc.",
    icon: Calendar,
  },
  {
    id: "pdf",
    label: "PDF Document",
    description: "Download a printable version of your plan",
    icon: FileText,
  },
  {
    id: "share",
    label: "Share Link",
    description: "Create a link to share your plan with others",
    icon: Share2,
  },
];

const LOCAL_PLANS_KEY = "fts_local_plans";

function generateICSContent(planName: string, items: any[]): string {
  const now = new Date();
  const formatDate = (date: Date) => date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  
  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Flip the Switch//Wellness Plan//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${planName}`,
  ];

  items.forEach((item, index) => {
    const eventStart = new Date(now);
    eventStart.setHours(parseInt(item.time?.split(':')[0] || '9'), parseInt(item.time?.split(':')[1] || '0'));
    const eventEnd = new Date(eventStart);
    eventEnd.setMinutes(eventEnd.getMinutes() + (item.duration || 30));

    icsContent.push(
      'BEGIN:VEVENT',
      `UID:fts-${Date.now()}-${index}@fliptheswitch.app`,
      `DTSTAMP:${formatDate(now)}`,
      `DTSTART:${formatDate(eventStart)}`,
      `DTEND:${formatDate(eventEnd)}`,
      `SUMMARY:${item.title || 'Wellness Activity'}`,
      `DESCRIPTION:Generated by Flip the Switch`,
      'END:VEVENT'
    );
  });

  icsContent.push('END:VCALENDAR');
  return icsContent.join('\r\n');
}

export default function ExportPage() {
  const [, params] = useRoute("/export/:planId");
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportComplete, setExportComplete] = useState(false);

  const planId = params?.planId;

  const getPlan = () => {
    try {
      const stored = localStorage.getItem(LOCAL_PLANS_KEY);
      const plans = stored ? JSON.parse(stored) : [];
      return plans.find((p: any) => p.id === planId) || { name: "My Plan", scheduleItems: [] };
    } catch {
      return { name: "My Plan", scheduleItems: [] };
    }
  };

  const plan = getPlan();

  const handleExport = async () => {
    if (!selectedFormat) return;
    
    setIsExporting(true);
    
    await new Promise(resolve => setTimeout(resolve, 1500));

    if (selectedFormat === "ics") {
      const icsContent = generateICSContent(plan.name, plan.scheduleItems || []);
      const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${plan.name.replace(/\s+/g, '-').toLowerCase()}.ics`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Calendar exported",
        description: "Your plan has been downloaded as an ICS file.",
      });
    } else if (selectedFormat === "pdf") {
      toast({
        title: "PDF export",
        description: "PDF export will be available in a future update.",
      });
    } else if (selectedFormat === "share") {
      const shareUrl = `${window.location.origin}/plans/${planId}`;
      await navigator.clipboard.writeText(shareUrl);
      toast({
        title: "Link copied",
        description: "Share link has been copied to your clipboard.",
      });
    }
    
    setIsExporting(false);
    setExportComplete(true);
  };

  return (
    <div className="min-h-screen bg-background">
      <PageHeader title="Export Plan" backPath="/plans" />
      
      <ScrollArea className="h-[calc(100vh-57px)]">
        <div className="p-4 max-w-lg mx-auto space-y-6 pb-8">
          <Card>
            <CardHeader>
              <CardTitle>{plan.name}</CardTitle>
              <CardDescription>
                Choose how you want to export your plan
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Badge variant="outline">{(plan.scheduleItems || []).length} items</Badge>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-3">
            {EXPORT_OPTIONS.map(option => {
              const Icon = option.icon;
              const isSelected = selectedFormat === option.id;
              
              return (
                <Card
                  key={option.id}
                  className={`cursor-pointer transition-all ${
                    isSelected ? "ring-2 ring-primary" : "hover-elevate"
                  }`}
                  onClick={() => setSelectedFormat(option.id)}
                  data-testid={`card-export-${option.id}`}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                        <Icon className="w-6 h-6 text-primary" />
                      </div>
                      <div className="flex-1">
                        <h3 className="font-medium">{option.label}</h3>
                        <p className="text-sm text-muted-foreground">{option.description}</p>
                      </div>
                      {isSelected && (
                        <Check className="w-5 h-5 text-primary shrink-0" />
                      )}
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>

          <div className="flex gap-3">
            <Button
              variant="outline"
              onClick={() => setLocation("/plans")}
              className="flex-1"
              data-testid="button-cancel-export"
            >
              Cancel
            </Button>
            <Button
              onClick={handleExport}
              disabled={!selectedFormat || isExporting}
              className="flex-1 gap-2"
              data-testid="button-export"
            >
              {isExporting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Exporting...
                </>
              ) : exportComplete ? (
                <>
                  <Check className="w-4 h-4" />
                  Exported
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Export
                </>
              )}
            </Button>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
